title: "Daniel Ross Portfolio"
description: "Showcasing my UX/UI design work and projects."
baseurl: "" # Leave blank for GitHub Pages
url: "https://jenkemchic.github.io/daniel.ross"

# Jekflix Theme Configuration
theme: jekflix-theme
paginate: 6
paginate_path: "/page:num/"
cover: "/assets/img/cover.jpg"  # Change to your cover image if needed
logo: "/assets/img/logo.png"  # Change to your logo if needed

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 6
paginate_path: "/page:num/"
theme_color: "#ff0000"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-content
  - jekyll-sass-converter
