title: "Daniel Ross Portfolio"
description: "Showcasing my UX/UI design work and projects."
baseurl: "" # Leave blank for GitHub Pages
url: "https://jenkemchic.github.io/daniel.ross"

# Jekflix Theme Configuration
theme: jekflix-theme
paginate: 6
paginate_path: "/page:num/"
cover: "/assets/img/cover.jpg"  # Path to the cover image
logo: "/assets/img/logo.png"  # Path to the site logo
author: "Daniel Ross"
email: "your-email@example.com"
twitter_username: "your_twitter"  # Remove if not using Twitter
github_username: "JenkemChic"

# SEO & Social Media
social:
  github: "https://github.com/JenkemChic"
  linkedin: "your-linkedin-profile-url"
  twitter: "your-twitter-profile-url"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 6
paginate_path: "/page:num/"
theme_color: "#ff0000"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-content
  - jekyll-sass-converter

# Google Analytics (Optional)
google_analytics: "UA-XXXXXXXXX-X"

# Disqus Comments (Optional)
disqus:
  shortname: "your-disqus-shortname"

