# Site settings
title: Daniel Ross
email: your-email@domain.com  # Add your actual email here
url: "https://jenkemchic.github.io"
description: "Daniel Ross is a UX Designer & Frontend Developer with expertise in Python, JavaScript, and UI/UX design."
keywords: "UX Design, Frontend Development, Python, JavaScript, User Experience"
skills: "UX/UI Designer - Frontend Developer - Creative Technologist"
meta_author: Ross Daniel

# GitHub Pages settings
baseurl: "/daniel.ross"  # Ensure this matches your repo name!
url: "https://jenkemchic.github.io"

# Google webmaster tools
google_verify:

# Bing webmaster tools verification
bing_verify:

# Contact form
contact: static  # Uses Formspree.io for contact form

# Disqus comments
disqus_shortname:

# Color settings (hex-codes without the leading #)
color:
  primary: 18bc9c  # Default theme color
  primary-rgb: "24,188,156"
  secondary: 2c3e50
  secondary-dark: 233140

# Footer settings
footer:
  copyright: "© 2025 Daniel Ross"
  location: "Based in the USA"
  social: "Follow Me"
  credits: "Designed & Developed by Daniel Ross"

# Social media (Update these with your actual links)
social:
  - title: twitter
    url: "https://twitter.com/yourhandle"
  - title: linkedin
    url: "https://www.linkedin.com/in/danielross"
  - title: github
    url: "https://github.com/JenkemChic"
  - title: dribbble
    url: "https://dribbble.com/yourprofile"
  - title: medium
    url: "https://medium.com/@yourprofile"

# Postal address (Optional)
address:
  - line: "Available for remote work worldwide"
  - line: "Currently based in the USA"

# Credits content
credits: 'Theme adapted from <a href="http://startbootstrap.com">Start Bootstrap</a>. Customized by Daniel Ross.'

# Build settings
markdown: kramdown
permalink: pretty

# Default settings for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

# Footer settings
footer:
  copyright: "Daniel Ross"
  location: "Based in [Your City, State]"  # Update location
  social: "Find Me Online"
  credits: "Built with a customized Freelancer Theme"

# Social networks (Update with actual URLs)
social:
  - title: github
    url: "https://github.com/JenkemChic"
  - title: linkedin
    url: "https://www.linkedin.com/in/your-profile"
  - title: twitter
    url: "https://twitter.com/your-handle"
  - title: portfolio
    url: "https://your-portfolio-url.com"

# Postal address (optional, or remove)
address:
  - line: "Available for Remote & In-Person Projects"
  - line: "Email me at: youremail@domain.com"

# Credits
credits: "This portfolio showcases my work as a UX Designer, Web Developer, and Digital Artist."
